### PR TITLE
feat: Support Go

### PR DESCRIPTION
**Pull request by lym953**
### What does this PR do?

Support Golang. 

Some details:
- creates a git tag `v2-1.14.0` to make this commit found easily when we later send it to Go package library
- makes gitignore un-ignore `/dist/go`, where the Go package is outputted, so the Go package code can be tracked by Git and uploaded. Currently the entire `/dist` folder is ignored.
- adds `/dist/go` to `.gitattributes` so that these generated files will be collapsed on GitHub, to avoid making code review difficult.

### Motivation
From [Feature Request: Datadog CDK Construct for Go](https://datadoghq.atlassian.net/browse/FRSLES-665)

### Testing Guidelines
I don't know a way to test it at this stage.
My planned next steps are:
1. After this PR is merged, visit https://pkg.go.dev/github.com/DataDog/datadog-cdk-constructs@v2-1.14.0 to request Go package library to include this repo
2. Install this package in a Go project and test it.
3. Update `README.md`
4. Write a release note for v2-1.14.0

Please let me know if there's a good way to test it at this state, or there are other next steps I should take.

### Types of Changes

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

**Review by astuyve — APPROVED** [review]
This looks awesome, thanks!! Let's make sure that publishing to npm is unaffected but I think the script should be fine, `tsc` SHOULD blow away the `dist` directory and then re-build.

Sweet!

**Review by aliciascott — APPROVED** [review]

**Comment by lym953** [comment]
Renamed the Go package from `datadog-cdk-constructs-v2` to just `datadog` because:
1. according to [Package names](https://go.dev/blog/package-names) and [Effective Go: Names](https://go.dev/doc/effective_go#names), package names:
    1. are in lower case. No upperCase or under_scores.
    2. are short
    3. don't need to be globally unique
2. Quite a few packages from Datadog are just called `datadog` ([search result](https://pkg.go.dev/search?limit=25&m=package&q=datadog)). I don't think it's likely that a client code file that uses our Datadog CDK Construct V2 package will likely use another Datadog package.

**Comment by lym953** [comment]
Talked with @astuyve and renamed the package as `ddcdkconstruct`.

**Pull request merged**
