### PR TITLE
feat: add node 18

### LINKED ISSUE #131: Add support for the node 18 lambda runtime
## Expected Behavior

[Release 6.85 of datadog-lambda-js](https://github.com/DataDog/datadog-lambda-js/releases/tag/v6.85.0) includes support for Node18. Ideally the new handler redirection can also be used: https://github.com/DataDog/datadog-lambda-js/pull/308

## Actual Behavior

Currently only older versions of node are supported

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Datadog Lambda Layer version: 
  - Node version: 
  
## Stacktrace
  
  ```
  Paste here
  ```

### PR DESCRIPTION
**Pull request by matthias-pichler-warrify**
### What does this PR do?

Add support for the Node 18 lambda runtime

### Motivation

We want to upgrade to the newest runtime. Closes #131  

### Types of Changes

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog

### CODE REVIEW

**Comment by automartin5000** [comment]
Might want to tag a reviewer like maybe @astuyve

**Comment by matthias-pichler-warrify** [comment]
@astuyve can this be merged?

**Comment by automartin5000** [comment]
> @astuyve can this be merged?

And released? 😅 I might've broken APM on a couple Lambda functions upgrading them to Node 18 😬

**Comment by astuyve** [comment]
Hi, yes I can do a release shortly!

**Comment by automartin5000** [comment]
Hey @astuyve still planning to do a release? Just trying to evaluate if I should stick with Node18 or roll back to 16

**Comment by astuyve** [comment]
Hi, when testing this PR I ran into other issues with our dependency on aws-cdk 2.24 and am still working to resolve them correctly, I will release as soon as those are resolved, but it will require a new PR.

**Comment by automartin5000** [comment]
Sounds good, thanks @astuyve!

**Pull request merged**
